name: panjnagam_api
channels:
  - default
dependencies:
  - python=3.9
  - bokeh=2.4.2
  - pip
  - pip:
    - fastapi
    - uvicorn
    - db-sqlite3
    - pytz
    - geopy
    - aksharamukha
    - uvicorn[standard]
